<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>OpenFno.Broker.Infrastructure</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql" />
    <PackageReference Include="StackExchange.Redis" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OpenFno.Broker.Application\OpenFno.Broker.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Persistence\schema.sql" LogicalName="schema.sql" />
  </ItemGroup>

</Project>
